export default {
  colors: {
    PRIMARY_BACKGROUND_BLUE: '#2B59C3',
    SECONDARY_BACKGROUND_WHITE: '#EFEFEF',
    SECONDARY_TITLE_WHITE: '#FFFFFF',
    PRIMARY_GRAY: '#CECCCC',
    SECONDARY_GRAY: '#949494',
    BORDER_GRAY: '#C9D4E2',
    DIVIDER_GRAY: '#F6F6F6',
    PRIMARY_WARNING_RED: '#F2545B',
    SECONDARY_WARNING_YELLOW: '#F2CD08',
    CLEAR_BLUE: '#00C2FF',
    DARK_GRAY: '#B7B7B7',
    SUCCESS_GREEN: '#59CD90',
  },
  fonts: {
    REGULAR: 'FiraSans_400Regular',
    MEDIUM: 'FiraSans_500Medium',
    SEMI_BOLD: 'FiraSans_600SemiBold',
    BOLD: 'FiraSans_700Bold',
  },
};
