export default {
  colors: {
    PRIMARY_BACKGROUND_BLUE: '#1A1B41',
    SECONDARY_BACKGROUND_WHITE: '#EFEFEF',
    SECONDARY_TITLE_WHITE: '#FFFFFF',
    PRIMARY_GRAY: '#CECCCC',
    SECONDARY_GRAY: '#949494',
    BORDER_GRAY: '#C9D4E2',
    DIVIDER_GRAY: '#F6F6F6',
    PRIMARY_WARNING_RED: '#F9564F',
    SECONDARY_WARNING_YELLOW: '#F2CD08',
    CLEAR_BLUE: '#42BFDD',
    DARK_GRAY: '#B7B7B7',
    SUCCESS_GREEN: '#20BF55',

    PRIMARY_TITLE: '#000000',
    SECONDARY_TITLE: '#525252',
    THIRD_TITLE: '#3D2929',
  },
  fonts: {
    REGULAR: 'FiraSans_400Regular',
    MEDIUM: 'FiraSans_500Medium',
    SEMI_BOLD: 'FiraSans_600SemiBold',
    BOLD: 'FiraSans_700Bold',
  },
};
